[package]
name = "flac-codec"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"

[dependencies]
arrayvec = "0.7.6"
bitstream-io = "4.1"
md5 = "0.7"
rayon = { version = "1.10", optional = true }

[dev-dependencies]
fastrand = "2.3"
